- README.md
- lib/email.js
- package.json
- test/integration/sendgrid.test.js
- test/lib/email.test.js
- test/lib/sendgrid.test.js
Depends on: https://github.com/sendgrid/smtpapi-nodejs/pull/14
Do not merge until the SMTPAPI NodeJS PR above have been merged.
> Adds ASM Group ID SMTPAPI Header setter

- .env.example
Fix environment variables in .env.example to accord with \test\integration\sendgrid.test.js.
```js
var API_USER    = process.env.SENDGRID_USERNAME || 'some_sendgrid_username';
var API_KEY     = process.env.SENDGRID_PASSWORD || 'some_sendgrid_password';
```
> Fix  environment variables.

- TROUBLESHOOTING.md
- package.json
Also update TROUBLESHOOTING.md, adding code to log error message.
> Update nodejs-http-client dependency to v2.3.0, closes #317

- lib/sendgrid.js
> Catch error in sendgrid

- examples/helpers/mail/example.js
> Fix typo in kitchen sink mail example

- packages/helpers/classes/mail.js
> Content is not mandatory

- CONTRIBUTING.md
Corrected the indentation of the sub-list points 4a and 4b, which were, earlier, not indented properly.
> Corrected sub-list indentation

- CODE_OF_CONDUCT.md
There was missing a CODE OF CONDUCT in the project, so I added one using the [weallbehave](https://github.com/WeAllJS/weallbehave) generator. The CODE OF CONDUCT is a community standard that establishes rules of how you should behave with the project.
Hope it helps 😊.
> Added CODE_OF_CONDUCT

- README.md
Added - Please Read First to the title.
> Added - Please Read First

- README.md
There was no mention of the word examples in the readme, which is solely about Developer experience. Added that.
> Added examples sections

- packages/mail/USE_CASES.md
> Update USE_CASES.md with Whitelabel and Email Statistics information

- CONTRIBUTING.md
- README.md
- packages/client/README.md
- packages/client/USAGE.md
- packages/client/USE_CASES.md
- packages/contact-importer/README.md
- packages/helpers/README.md
- packages/inbound-mail-parser/README.md
- packages/mail/README.md
- packages/mail/USE_CASES.md
Updates for SEO-ness (sendgrid/sendgrid-nodejs#515)
> SEO Friendly Section links

- packages/client/README.md
- Added missing closing parenthesis
> Fix markdown link

- README.md
> Added Badges on Redme

- packages/client/src/client.spec.js
- packages/contact-importer/src/importer.js
- packages/contact-importer/src/importer.spec.js
- packages/inbound-mail-parser/src/parser.js
- packages/inbound-mail-parser/src/parser.spec.js
converts all vars to let or const
> Moving away from var

- packages/helpers/classes/mail.js
- packages/helpers/classes/mail.spec.js
- packages/helpers/classes/personalization.js
- packages/helpers/classes/personalization.spec.js
added null check for setSubstitutionWrappers
@mbernier edit: fixes #527
> exclude headers from camel/snake case conversion, fixes #527

- packages/client/USAGE.md
> Fix a typo

- packages/client/src/client.js
- packages/mail/src/mail.spec.js
PR creates a typeof check for callback being passed to the client. and throws an error incase a callback which is not a function is passed.
> Callback type check

- .env_sample
- README.md
https://github.com/sendgrid/sendgrid-nodejs/issues/545
> updating readme.md with instructions on .env, and adding .env_sample

- TROUBLESHOOTING.md
Fixes #574 
- Fix the broken link to the example
> Fix broken link in handling errors sections

- .codeclimate.yml
- .eslintrc.yaml
Hi guys, added and verified the codeclimate.yml configs. What do you suggest for running the tests?
@mbernier edit: closes #557
> Add .codeclimate.yml for #557

- packages/helpers/helpers/array-to-json.js
Fixes #579
- Fixing complexity for arrayToJson helper
> simplify complexity in arrayToJson helpers

- packages/contact-importer/src/importer.spec.js
[] I have remove .only on test, to run all test suite
> Remove only on test

- packages/helpers/helpers/html-to-plain-text.js
- packages/helpers/helpers/html-to-plain-text.spec.js
contribution for Hacktoberfest.
#453
> -function removes html tags to string

- package.json
> Fixes #601: Chai dependency version issue.

- README.md
- Added tags for open source contrubut 
> updated readme tags

- packages/mail/USE_CASES.md
- Update the doc file "packages/mail/USE_CASES.md" to show how to enable tracking settings.
Reference issue: #744 
> Update docs to show an example on how to enable tracking settings.

- packages/client/USAGE.md
- packages/client/USE_CASES.md
- use-cases/README.md
- use-cases/email-activity.md
- Updates the USAGE.md and USE_CASES.md for the client
- Updates the use-cases with references to relevant documentation
> Add documentation for Email Activity API

- packages/inbound-mail-parser/package.json
- packages/inbound-mail-parser/yarn.lock
Closes #762 and closes #664. 
- [N/A] I have added tests that prove my fix is effective or that my feature works
- [N/A] I have added necessary documentation about the functionality in the appropriate .md file
- [N/A] I have added in line documentation to the code I modified
- Updates mailparser to latest version (^2.3.4)
> [inbound-mail-parser] fix(deps): Update mailparser to 2.3.4

- TROUBLESHOOTING.md
- [ x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [ x] I have read the [Contribution Guide] and my PR follows them.
- [ x] I updated my branch with the master branch.
- Fixed v3 email example broken link
> v3 send email broken link fixed in TROUBLESHOOTING.md

- LICENSE.md
- packages/client/USAGE.md
> Fix #863 Not able to get the template list

- .travis.yml
> Test against more Node.js versions

- packages/helpers/classes/mail.js
- packages/helpers/classes/personalization.d.ts
- test/typescript/helpers.ts
Fixed two issues:
1. Bug with incorrect dropping of `dynamicTemplateData` from personalization data
2. Correct type for `dynamicTemplateData`
> Fix personalizations dynamic bug

- packages/client/src/classes/client.js
Return promise with catch handler if callback provided to avoid returning a promise rejection
> Return promise with catch handler if callback provided

- use-cases/kitchen-sink.md
Spelling fix
- 
- 
If you have questions, please send an email to [Twilio SendGrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.
> docs: fix typo 'Feild' to 'Field'

- packages/helpers/package.json
- packages/helpers/yarn.lock
> fix: upgrade deepmerge to resolve webpack import issue

- packages/client/src/client.d.ts
> fix: update Client constructor property definition in TS declaration

- packages/mail/src/mail.d.ts
> fix: add 'setTimeout' to the MailService TS definition

- packages/client/src/classes/client.js
> fix: correct the User-Agent casing

- docs/use-cases/event-webhook.md
Adds a missing `new` to instantiate the `EventWebhook`.
If you have questions, please file a [support ticket](https://twilio.com/help/contact), or create a GitHub Issue in this repository.
> docs: Fix EventWebhook example in use case docs

- LICENSE
- packages/client/package.json
- packages/client/src/classes/client.js
* Bumps axios version dependency and related sendgrid version numbers
* Updated year in LICENSE to pass CI test
> chore: bump axios version

- README.md
- USAGE.md
- docs/use-cases/advanced.md
- docs/use-cases/attachments.md
- docs/use-cases/custom-headers.md
- docs/use-cases/customization.md
- packages/client/README.md
- packages/helpers/README.md
- packages/mail/README.md
Fixes broken links to API Docs. https://github.com/sendgrid/sendgrid-nodejs/issues/1250
> docs: Update API Docs link in Readme's

- TROUBLESHOOTING.md
A short description of what this PR does.
> docs: Update TROUBLESHOOTING.md - add JSON.stringify

- packages/mail/src/mail.d.ts
> fix: re-export ClientResponse and ResponseError

- README.md
Fix broken link to the Twilio SendGrid docs page.
> docs: fix broken docs link

- packages/helpers/classes/attachment.d.ts
Attachment's properties are inherently public, and need to be typed as such
A short description of what this PR does.
> fix: Updating attachment types

- packages/mail/src/mail.d.ts
- packages/mail/src/mail.spec.js
This reverts commit a6a83d135c79270f265acd6e7e44dfc3d7c382ea.
> Revert "chore: adjust 'packages/mail/src/mail.d.ts' (#1320)"

- packages/client/src/client.spec.js
- test/mocha.opts
1. Hitting gateway timeouts at 25MB payload size but works fine when I do an actual test with the large payload 
2. Seeing prism issues with 204s. Revisit when prism is upgraded to the latest version.
> test: get the integration tests running again

- packages/client/README.md
- packages/contact-importer/README.md
- packages/inbound-mail-parser/README.md
- packages/mail/README.md
The links in [npm](https://www.npmjs.com/package/@sendgrid/mail) didn't work for the troubleshooting doc
> docs: Fix troubleshooting in readme

- LICENSE
- docs/use-cases/data-residency-set-hostname.md
A short description of what this PR does.
> chore: update use-case & license year

- packages/client/package.json
Axios version has been updated to 1.6.4 to fix [this vulnerability](https://security.snyk.io/package/npm/axios/1.6.0)
> chore: fixed axios vulnerability

- .github/workflows/test-and-deploy.yml
Github has shifted to using `docker compose` (v2) by default. So installing `docker-compose` (v1) in the deploy script
> chore: install docker-compose

- packages/client/package.json
- this fixes recent CVE-2024-39338 Server-Side Request Forgery in axios (https://github.com/advisories/GHSA-8hc4-vh64-cxmj)
> chore: fixed axios vulnerability by upgrading 1.6.8 to 1.7.4

- LICENSE
A short description of what this PR does.
> chore: update licence year

- packages/client/package.json
this fixes recent https://github.com/advisories/GHSA-jr5f-v2jv-69x6 wherein axios requests are vulnerable to ssrf and credential leakage
> chore: fixed axios vulnerability by upgrading 1.7.4 to 1.8.2

- .github/workflows/test-and-deploy.yml
- package.json
- packages/client/package.json
1. Upgrading axios due to security vulnerability raised here - https://github.com/twilio/twilio-cli/security/dependabot/96
2. Use `make test` instead of `make test-docker`, for details, refer - https://github.com/sendgrid/sendgrid-python/pull/1117
> chore: Update axios dependency version to 1.12.0 in client
