sendgrid/sendgrid-nodejs

package.json

The sendgrid-nodejs project leverages the following lodash functions:
* isObject
* extend
* isEmpty
* merge
Based on the [lodash changelog](https://github.com/lodash/lodash/wiki/Changelog), `_.isObject` had some optimizations and `_.merge` had some sanity checks introduced (which wouldn't impact the usage within `sendgrid.js`).
All tests pass.
This PR tells sendgrid to permit both the v2 and v3 of lodash, but tells it to prefer the v3 branch.

Permit lodash version 3 to also be acceptable within npm

---

lib/email.js

This pull request enables setter method chaining as follows like sendgrid-java.
```js
var sendgrid  = require('sendgrid')(api_user, api_key);
email = new sendgrid.Email()
.addTo('example@example.com')
.setFrom('other@example.com')
.setSubject('Hello World')
.setText('My first email through SendGrid.');
```

Add 'return this' for setter method chaining

---

lib/sendgrid.js

Make SendGrid a factory that enables multiple prototype instances

---

.travis.yml
index.d.ts
package.json
tsconfig.json

Hi guys,
Recently updated an application of ours to use your 3.0.0 library and noticed there weren't any up to date typings files in the wild. Seeing as the current approach with TypeScript is to embed these definition files in their respective NPM modules, I've taken the time to put together a compatible set of type definitions for your library.
In addition to adding the raw type definitions, I've also taken the liberty of adding a quick test that ensures the definition file is well formatted, it should help ensure that things aren't broken accidentally going forward.
As far as manual verification of the typings file goes, aside from running your unit test suites through the TypeScript compiler to confirm that they comply with the typings file (always a good way to ensure the types match …

Add TypeScript typings definition file for v3 API

---

index.d.ts

See #251 and <https://github.com/SPARTAN563/sendgrid-ts-demo/pull/1> for more details on what wasn't working.
This ensures that the following code works correctly:
````typescript
import * as SendGrid from "sendgrid";
const sendGrid = SendGrid("MYAPIKEY");
``

fix: Correct TypeScript definitions

---

lib/sendgrid.js

This makes the behavior when using callbacks consistent with the promise counterpart.
That is, in both cases, `error.response` is present

Fill 'response' property in error instance

---

index.d.ts

Allow emptyRequest() to be called with a request object

---

index.d.ts

This should fix #307 by adding an overload definition for the `sg.API()` method which returns a promise when called without a second parameter (callback).

feat: Add support for promises to the TypeScript definitions file

---

lib/sendgrid.js

Convert response data to have valid json objects

---

index.d.ts

I think the [SendGrid.API](https://github.com/sendgrid/sendgrid-nodejs/blob/d01e7efb3a1f8f67435aec09ad633095ac322cc2/index.d.ts#L469) function should return a object on which either `.then()` or `.catch()` can be called upon.
The current implementation uses [PromiseLike<T>](https://github.com/Microsoft/TypeScript/tree/6814c1d883791a1ad976f3146315de30e00dc0b9/lib/lib.es6.d.ts#L1319) interface which only ensures `.then()`.
But the problem would be solved by using [Promise<T>](https://github.com/Microsoft/TypeScript/tree/6814c1d883791a1ad976f3146315de30e00dc0b9/lib/lib.es6.d.ts#L5221) interface instead.
```ts
SendGridClient
.API(request)
.then(okFunction)
.catch(noOkFunction)  // this line will not be reported as an error anymore
```
* sendgrid-nodejs Version: master (latest commit: …

[TypeDefinition] SendGrid.API should return Promise<T> instead of PromiseLike<T>

---

index.d.ts

This should address the issues faced in #353 while still ensuring that we accurately cover the type's requirements.
Please let me know if you have any concerns or further requests for this fix.
Regards,
Benjamin
/cc @sheyaweidberg

fix: Make various TypeScript request components optional

---

index.d.ts

Personalization.getSubstitutions() return type incorrect in index.d.ts TypeScript definition file

---

index.d.ts

Small fix, the current definition in index.d.ts of ClickTracking right now is ClickTracking(boolean, string) this one is giving a error from the API, so it should be ClickTracking(boolean, boolean)

Fix typescript definition for the ClickTracking

---

index.js
lib/helpers/inbound/parse.js
package.json
test/helpers/inbound/parse.test.js

An attempt of tackling issue #303. I've also pretty much done the bulk of the work around the Inbound Server Example and Send module, but will create separate PRs to make the reviewing easier.
Essentially my best effort of porting the python parse class to node (https://github.com/sendgrid/sendgrid-python/blob/master/sendgrid/helpers/inbound/parse.py)
**Changelog:**
- Adds [mailparser](https://www.npmjs.com/package/mailparser) npm dependency (required for parsing raw emails)
- Adds `parse.js` module
- Adds simple unit tests of the parse module
Example usage:
``` node
var Parse = require('sendgrid').parse;
var config = {
keys: ['to', 'from', 'subject']
};
var parse = new Parse(config, request); 
// Get Key Values
console.log(parse.keyValues());
// Get Attachments …
```

Add Inbound Parse data parser #303

---

.travis.yml
CONTRIBUTING.md
README.md
package.json

As discussed in #325 with @thinkingserious - PR to drop support for end-of-life Node.js v0.10 as of 01-Nov-2016. Also include Node.js LTS v6 in the list of supported versions, as all tests pass (using Prism).

Drop 0.10, 0.12 from supported Node.js versions, add 6

---

README.md

The PR title describes the change in its entirety really. I am proposing adding a `npm version` badge to the top of the README file. This little informative badge allows people to click on it and easily jump to the npm listing (just like the Travis CI badge does already for code integration tests) and informs people about which version is actually up on npm. For those who do not care about either one of those benefits do not have to be worried - this little badge does not take up much space and is simply not in their way then.

Add a badge for `npm version`

---

README.md

The proposed change:
- ~switches from `var` to `let` for cleaner scoping of variables.~
- ~switches all function expressions to arrow function expressions as to provide an easier overview.~
- removes trailing commas - although valid and arguably wildly used, not really a part of any standardization.
- adds semicolons where missing - mixing use of semicolons and avoiding them in the same codebase is not a good idea and since most of the examples do have semicolons after statements I am adding them where they were missing instead of removing the ones that were there but could be dropped.
- ensures comments start with a single space for consistency and readability.
- adds an error handling if clause to the first example.
- cleans up the source for displaying the logo as well as the _use …

Restructure README example code

---

lib/helpers/contact-importer/contact-importer.js

Since 4.6.0, the `response.body` is a parsed object, rather than a JSON string. This fixes the contact-importer to not try to parse them itself, and allows its tests to pass again.

Remove JSON.parse() around response bodies in contact-importer

---

.travis.yml
package.json
test/prism.sh
test/test.js

Refs #316 
I wanted to implement this as I thought I should have working tests before looking at any other issues.
Maybe @tsriram and I could collaborate on this?
Current limitations; does not work on Node 0.10 or 0.12, which are both at or near end-of-life... (as a bonus, it does pass on Node 6, as well as 4 and iojs). 
Please let me know if I'm working along the right lines.

[WIP] Run prism for tests

---

lib/helpers/mail/mail.js

There is a problem when you send a sendgrid request with model created by `helper.Mail` personalizations does not converter to JSON.
I fixed this.

Return personalizations as an array of request compatible JSON.

---

index.d.ts

`batch_id` is a string according to[ Sendgrid documentation](https://sendgrid.com/docs/API_Reference/api_v3.html), but in `index.d.ts` file `batch_id` is considered a number.

Fix `batch_id` type

---

lib/helpers/mail/mail.js

This allows for numbers as well as strings for substitution values. Could still use some type checking and error handling to inform the user if they send an object (which also has a `toString` method, so won't throw) or other invalid value type.
Fixes #282.

Cast substitution values to strings

---

lib/helpers/mail/mail.js

After #410 we started getting errors like `TypeError: Cannot read property 'toString' of null`. This tests for null or undefined values and handles them as empty string.

Handle null and undefined values in substitutions

---

index.d.ts

This PR expands on the suggestion of #417 to ensure that the type of the error is correct.

fix: Update TypeScript definition to correct callback arguments for API

---

package.json
packages/contact-importer/package.json
packages/contact-importer/src/importer.js
packages/contact-importer/src/importer.spec.js

Also add `sendgrid` as a dependency so the test will run and pass.
Resolves #532

Turn ContactImporter into ES6 class

---

packages/subscription-widget/LICENSE.txt

The main [LICENSE](https://github.com/lvarayut/sendgrid-nodejs/blob/4f73c88cd2800072835c63826a32aff898d9d444/LICENSE.md#L1) file has the correct year range. However, only the LICENSE file in the `subscription-widget` has the wrong range. This PR corrected it with the same year range specified in the main LICENSE file.
Fixed #562

Update the license file to have the correct date range

---

.travis.yml
license.spec.js
package.json

The LICENSE file is read and checked if the end year is current year or not.
Closes #563

Add a unittest to check the license.md file date range

---

packages/client/USAGE.md

Updated the endpoint which allows the retrieval of all recipients

---

packages/helpers/classes/response-error.js

Catched this error when testing with a dummy API key.
```
TypeError: Cannot read property 'errors' of undefined
at ResponseError.toString (.../node_modules/@sendgrid/helpers/classes/response-error.js:45:27)
at parseStackAndMessage (.../node_modules/bluebird/js/release/debuggability.js:574:25)
at CapturedTrace.attachExtraTrace (.../node_modules/bluebird/js/release/debuggability.js:778:18)
```
After adding the simple check `if (body && Array.isArray(body.errors))` the "Unauthorized (401)" error is properly returned as promise rejection.

Check if "body" on "response" is actually defined before accessing it

---

packages/client/src/client.d.ts
packages/helpers/classes/email-address.d.ts
packages/mail/src/mail.d.ts

i've updated the definitions files to support typescript 2.6. fixes #618

fix: update definitions for tsc 2.6, fixes #618

---

packages/mail/USE_CASES.md

Change `contentId` to `content_id`

---

README.md

- added link to sendgrid docs in the readme
- 
Fixes #679

Added link to docs from README #679

---

packages/client/USE_CASES.md
packages/mail/USE_CASES.md

Added how to deploy simple hello world app on Azure

---

README.md

- [ X] I have read the [Contribution Guide] and my PR follows them.
- [ X] I updated my branch with the master branch.
- [X ] I have added necessary documentation about the functionality in the appropriate .md file
- There was a broken link to an old job posting.  I replaced that with the general Careers page.

Fix outdated careers link

---

packages/helpers/attachment.txt
packages/helpers/classes/attachment.js
packages/helpers/classes/attachment.spec.js

Fixes #394

---

packages/subscription-widget/package.json

If you execute `lerna bootstrap` it will try to install `subscription-widget` and it will fail:
```
lerna ERR! yarn install --mutex network:42424 --non-interactive stderr:
warning Waiting for the other yarn instance to finish (5655)
warning Waiting for the other yarn instance to finish (5674)
error @sendgrid/subscription-widget@6.2.1: The engine "node" is incompatible with this module. Expected version "4.1.1".
error Found incompatible module
```
This is due the node version being locked to a old version of node (`4.1.1`). This PR changes the node version to be compatible with all the other packages (`>=6.0.0`)

Fix subscription-widget node engine version

---

packages/client/package.json

- Upgrading request dependency to latest to fix inner dependency `request@2.83.0 > hawk@6.0.2 > hoek@4.2.0` vounrability

Upgrade request to 2.88.0 (latest) to address issue #661

---

packages/helpers/classes/mail.d.ts

The library doesn't send dynamicTemplateData added to the personalization to the SendGrid API.
dynamicTemplateData in the MailData works.
- 
- 

MailData must have dynamicTemplateData property

---

README.md

Updated README to include the CLA (Contributor Licensing Agreement) for this repo
- Adds a CLA (Contributor License Agreement in README.md section

Update README.md to include the CLA

---

examples/inbound-parse-docker/.dockerignore
examples/inbound-parse-docker/.gitignore
examples/inbound-parse-docker/CONTRIBUTING.md
examples/inbound-parse-docker/Dockerfile
examples/inbound-parse-docker/LICENSE
examples/inbound-parse-docker/README.md
examples/inbound-parse-docker/app.js
examples/inbound-parse-docker/docker-compose.debug.yml
examples/inbound-parse-docker/docker-compose.yml
examples/inbound-parse-docker/example-webhook-payload.txt
examples/inbound-parse-docker/k8s/inbound-parse.yml
examples/inbound-parse-docker/package-lock.json
examples/inbound-parse-docker/package.json

#787 
- This is a docker container that can receive Inbound Parse webhooks from SendGrid

Add inbound parse webhook example

---

TROUBLESHOOTING.md

kubernetes secrets "\n" problem FIX.

---

CODE_OF_CONDUCT.md

- Updated the OSI code of conduct link with another one with the same content but with better formatting and styling (so it's easier to read; the current one display the entire thing as a single string).

Update OSI code of conduct link

---

packages/helpers/classes/mail.js
packages/helpers/classes/mail.spec.js
packages/helpers/constants/index.js
use-cases/transactional-templates.md

- Warns if any of the ', " or & characters are used in a dynamic template that does not escape with triple-stash syntax

Warn if dynamic template contains non-escaped character

---

TROUBLESHOOTING.md

- Update the link for environment variables to the correct one

Correct link for environment variables setup

---

TROUBLESHOOTING.md

- **Html tags to support line wrap while writing the mail.**
- Added the #692 multi-line codes in pre turn to one line after mail send, to the troubleshooting.md on your request.

#765 - Updating the troubleshooting.md

---

use-cases/customization.md
use-cases/kitchen-sink.md

- Update mentions of `customArgs` field in the docs to reflect that it takes only string value
- Add an error handling section to the kitchen sink example to notify future users.
cc @thinkingserious

docs: specify custom arguments must have string values

---

CONTRIBUTING.md

- [ x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [ x] I have read the [Contribution Guide] and my PR follows them.
- [ x] I updated my branch with the master branch.
- Fixed USAGE link
- Fixed USE_CASE link
- Fixed esdoc link

Contributing.md broken links fix

---

packages/contact-importer/README.md
packages/contact-importer/package.json
packages/contact-importer/src/importer.js
packages/contact-importer/src/importer.spec.js
packages/contact-importer/yarn.lock

Closes #427 
- Upgrade contact-importer to use @sendgrid/client v6.X

[contact-importer] Update to support @sendgrid/client v6.X

---

.eslintignore
.eslintrc.yaml
.travis.yml
CONTRIBUTING.md
package.json
packages/inbound-mail-parser/src/parser.spec.js
packages/mail/src/classes/mail-service.js
packages/subscription-widget/server/controllers/contact_list_controller.js

Fixes #766
Update ESLint rules as follows:
- exclude `global-require` errors (245 occurrences)
- set `complexity` and `max-statements` to `warn`
Fix remaining ESLint errors.
Add npm run script for ESDoc.
Add TravisCI scripts for ESLint and ESDoc.

Add conformance to style standards

---

packages/mail/USE_CASES.md

Clarified how you can change the sender name, which was not entirely obvious. Also added it to the "kitchen sink" example and fixed the link to that section in the table of contents.
- [ x ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [ x ] I have read the [Contribution Guide] and my PR follows them.
- [ x ] I updated my branch with the master branch.
- [  ] I have added tests that prove my fix is effective or that my feature works
- [ x ] I have added necessary documentation about the functionality in the appropriate .md file
- [  ] I have added in line documentation to the code I modified
Some minor documentation updates.
If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this …

Clarified how you can change the sender name

---

.travis.yml

Description of the change: Updated .travis.yml
Reason for the change: Added this so that code coverage tests run
@thinkingserious @ksigler7 Please review :)

Added the lines to .travis.yml as requested

---

packages/client/USAGE.md

- updated USAGE.md to cover #440

updated usage for /categories/stats

---

packages/client/README.md
packages/helpers/classes/attachment.js

- Fix documentation referencing `sgClient` instead of `client`
- Fix indentation being tabs rather than spaces in Attachment class

Fix readme instructions and replace stray tab indentation by spaces

---

packages/helpers/classes/index.js
packages/helpers/classes/statistics.d.ts
packages/helpers/classes/statistics.js
packages/helpers/classes/statistics.spec.js

Add statistics helper class

---

packages/helpers/classes/email-address.js
packages/helpers/classes/email-address.spec.js

Resolves #448 
- Wrap name in quotes if it contains a comma as suggested [here](https://github.com/sendgrid/sendgrid-csharp/issues/268#issuecomment-232177443)
- Add test cases

Comma bug in name #448

---

packages/mail/src/classes/mail-service.js

- Added the methods:
- setSecretRules: user can configure a set of named rules to test the
e-mail content;
- filterSecrets: this method test all the e-mail content with the
rules configured in setSecretRules, nothing is done if secretRules
is empty, and if a rule is found in the e-mail content, then a
exception is thrown;
- The method filterSecrets is called before the request to the API and
should prevent sensitive data leakage;
@mbernier edit:
closes #496

Prevent secrets from sending in email

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

- SendGrid was improperly capitalized in the **Contact the Moderators** line
- 

Fixed capitalization for "SendGrid" in **Contact the Moderators**

---

packages/mail/USE_CASES.md

Fix typo in USE_CASES.md

---

.github/PULL_REQUEST_TEMPLATE
.github/PULL_REQUEST_TEMPLATE.md
packages/client/src/classes/client.js
packages/contact-importer/src/importer.js

Ensure the SendGrid brand is proprely capitalized in the entire repo: **S**end**G**rid

Properly capitalize "SendGrid" brand

---

.travis.yml
packages/mail/src/classes/mail-service.js

Fixes the Travis CI build on master caused by merges of #582, #767 and #502.
- Resolve ESLint errors caused by merge of #767 and #502
- Revert merge of #586 that caused initial build failure on master as shown here: https://travis-ci.org/sendgrid/sendgrid-nodejs/builds/444800868
#586 is marked as fixing #582 (Add CodeCov support to .travis.yml) but it does not appear the changes are sufficient. #598 appears to be a more complete fix.

Fix Travis CI build failures on master

---

packages/helpers/classes/attachment.js
packages/helpers/classes/attachment.spec.js

- Added the method readFile to read a file and convert its content to
base64;
- It's now possible create an Attachment with a raw file;

Attachment helper for base64 encoding

---

packages/inbound-mail-parser/src/parser.d.ts
packages/inbound-mail-parser/src/parser.js
packages/inbound-mail-parser/src/parser.spec.js

- Fix parser constructor error when passing `payload` instead of `body`

Fix parser constructor error when passing payload

---

packages/helpers/classes/mail.d.ts
packages/helpers/classes/mail.js
use-cases/README.md
use-cases/hide-warnings.md

-  Allows hiding warnings by using a "hideWarnings" parameter in the Mail class.

Allows hiding warnings

---

packages/helpers/classes/personalization.js

Fixes #899  
This PR fixes webpack's interpolation issue with the deepmerge package. Related to the changes made to [deepmerge](https://github.com/TehShrike/deepmerge/pull/124). Renaming `merge` to `deepmerge` fixes the issue.

Fixed deepmerge module export naming issue

---

packages/helpers/constants/index.js

- [ X] I acknowledge that all my contributions will be made under the project's license
- [ X] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [X ] I have read the [Contribution Guide] and my PR follows them.
- [N/A] I updated my branch with the development branch.
- [ N/A ] I have added tests that prove my fix is effective or that my feature works
- [ N/A] I have added necessary documentation about the functionality in the appropriate .md file
- [ N/A ] I have added in line documentation to the code I modified
- The link in warning for `DYNAMIC_TEMPLATE_CHAR_WARNING` was to old url
- 
If you have questions, please send an email to [Twilio SendGrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

Update url in "DYNAMIC_TEMPLATE_CHAR_WARNING" to point to a working current link

---

package.json

chai is only needed as a development dependency.

fix: remove chai from dependencies

---

packages/client/package.json

Fixes #1027. 
This moves the `@types/request` dependency back into the non-dev category, unbreaking the package for TypeScript users. This is described as best practice here:
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#dependencies
I also bumped the version up from 2.0.4, which was [two years old](https://www.npmjs.com/package/@types/request), to 2.48.4. I am unsure how DefinitelyTyped versions their types packages... but request v2.88.0 is the most recent version on NPM, so I assume y'all want the latest @types/request version also.

fix #1027: Move @types/request back to dependencies

---

packages/mail/src/mail.d.ts

Before, `{MailService: MailService}` suggested an instance of `MailService` was being passed. Changing the syntax to ~~`{new(): MailService}`~~ `typeof MailService` suggests that it's a callable constructor reference available as a property
- 
- 
If you have questions, please send an email to [SendGrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

fix: update MailService constructor property definition in TypeScript declaration

---

packages/client/USAGE.md

The documentation recommends urlencoding data when checking message activity.
This causes a double encoding problem.
- Updates documentation to prevent double encoding of queries
- 
If you have questions, please send an email to [SendGrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

docs: Update USAGE.md to prevent query double encoding

---

packages/mail/README.md

explicitly stating that the send() method returns a promise
- 
- 
If you have questions, please send an email to [Twilio SendGrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

docs: Update README.md to explicitly state that 'send()' returns a promise

---

.github/PULL_REQUEST_TEMPLATE
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
examples/webhooks-docker/CONTRIBUTING.md
packages/client/README.md
packages/helpers/README.md
packages/inbound-mail-parser/README.md
packages/mail/README.md
packages/subscription-widget/README.md
use-cases/transactional-templates.md

Properly capitalize **S**end**G**rid and **G**it**H**ub

docs: Properly capitalize Brands

---

README.md

- [ X] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [X ] I have read the [Contribution Guide] and my PR follows them.
- [X ] I updated my branch with the master branch.
- [X ] I have added tests that prove my fix is effective or that my feature works
- [ X] I have added necessary documentation about the functionality in the appropriate .md file
- [X ] I have added inline documentation to the code I modified
- Fixed two gramatical errors in the README.md file
- 

docs: Fix grammatical errors in README

---

packages/mail/src/mail.d.ts

fix: require in TS at least 1 type of content for sending mail

---

packages/helpers/classes/mail.d.ts
packages/mail/src/mail.d.ts

Exposes the new mail properties type `MailDataRequired` that was added in https://github.com/sendgrid/sendgrid-nodejs/pull/1041

chore: export type MailDataRequired

---

packages/contact-importer/src/importer.js

- Fix issue with `request` package, it is looking for `URI` or `URL` when `baseUrl` is set, 
If you have questions, please send an email to [Twilio SendGrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

Fix: options.uri must be string

---

.travis.yml
package-lock.json
package.json
packages/helpers/classes/attachment.js
packages/helpers/classes/attachment.spec.js
yarn.lock

- replaces babel-preset-es2015 (deprecated) by babel-preset-env
- add testing voor nodejs 10
- [x ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x ] I have read the [Contribution Guide] and my PR follows them.
- [x ] I updated my branch with the master branch.
- [x ] I have added tests that prove my fix is effective or that my feature works
- [x ] I have added necessary documentation about the functionality in the appropriate .md file
- [x ] I have added inline documentation to the code I modified

fix: correct the attachment file path test

---

packages/client/src/classes/client.js
packages/client/src/client.spec.js

feat: console warning added when using an invalid API key

---

docs/use-cases/time-to-send.md

Document that cancelling is not possible, without suggesting an alternative.

docs: document sendAt limitations

---

packages/mail/src/mail.d.ts

fix: correct the mail TS exports

---

packages/client/USAGE.md

The use case of performing API calls on behalf of subusers is not documented.
While we're waiting on #600 to provide an interface to supply the subuser username,
this PR is a quickfix to at least document how to set the `on-behalf-of` header
to accomplish the use case.
If you have questions, please file a [support ticket](https://twilio.com/help/contact), or create a GitHub Issue in this repository.

docs: add documentation on the on-behalf-of header usage

---

packages/client/src/classes/client.js
packages/client/src/client.spec.js

Fixes https://github.com/sendgrid/sendgrid-nodejs/issues/1106

fix: don't limit the request content length

---

docs/use-cases/kitchen-sink.md

The documentation in [kitchen-sink.md](https://github.com/sendgrid/sendgrid-nodejs/blob/master/docs/use-cases/kitchen-sink.md) has a typo. According to the [mail](https://github.com/sendgrid/sendgrid-nodejs/blob/e29d125629bad8e21ca695c9ad23d429a33c8ae6/packages/helpers/classes/mail.d.ts#L34) class it should be `sandboxMode` not `sandbox`.
I discovered this after sending several dozen emails thinking the sandbox mode was enabled, oops!

docs: Fixing sandbox key in kitchen-sink documentation

---

.travis.yml
lerna.json

Updating from node v0.10.48 to v10.20.1 since `lerna` requires node >= v6.9.0.

fix: update node version in travis for deploy via lerna

---

.travis.yml

Fixes bug introduced in #1123 where node version was v10 for all builds.
This also undoes some changes introduced in #1112 but looking at the travis builds, the version wasn't being set properly.

fix: travis autodeploy

---

packages/mail/README.md

If you are just testing this out in development and follow the instructions either here on github or inside the sendgrid web app it never mentions you must first verify a "from" domain or single address. 
You will simply receive a 403 forbidden response on trying to send any mail, including the example email.
The error response does contain an error message though by default it won't be visible due to the way node simplifies deeply nested objects in `console.log`, as you can see below. 
The actual error message does display if you know where to look `error.response.body` but at first glance and from the current docs you just think maybe your API keys aren't set up right.
One or two lines in the docs should prevent this.
```
ResponseError: Forbidden
at …
```

docs: Update docs for domain or email verification

---

docs/use-cases/transactional-templates.md

This fixes a typo in the docs. It can lead devs down the wrong path. Related PR: #716
If you have questions, please file a [support ticket](https://twilio.com/help/contact), or create a GitHub Issue in this repository.

docs: Update transactional-templates.md to use dynamicTemplateData instead of dynamic_template_data

---

docs/use-cases/event-webhook.md
packages/eventwebhook/index.d.ts
packages/eventwebhook/src/eventwebhook.d.ts
packages/eventwebhook/src/eventwebhook.js
packages/eventwebhook/src/eventwebhook.spec.js
test/typescript/eventwebhook.ts

Fixes #1142 
This PR updates the event webhook verification interface to accept string and Buffer type payloads, the preferred means of processing the event webhook request body. PR also adds the `EventWebhookHeader` class as well as a usage example.

fix: event webhook interface to process raw body

---

use-cases/attachments.md

Added use cases for adding attachments  and encode to base 64. From a local PDF file and using an URL (this example was tested using an AWS S3 bucket URL)
- [x ] I have added inline documentation to the code I modified
- Added use cases for reading, encoding PDF. Also using an URL. 
- 
If you have questions, please send an email to [SendGrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

docs: add more use cases for adding attachments

---

packages/client/USAGE.md
packages/client/USE_CASES.md
packages/mail/USE_CASES.md
use-cases/README.md
use-cases/domain-authentication.md
use-cases/domain-authorization.md
use-cases/domain-white-label.md

Per the SendGrid Docs [here](https://github.com/sendgrid/docs/blob/develop/content/docs/glossary/whitelabel.md) as well as an upcoming addition to the Docs in a PR I have submitted [here](https://github.com/sendgrid/docs/pull/4182#discussion_r224903380), the term "Whitelabel" is no longer being used in SendGrid documentation and has been "deprecated" ([see here](https://github.com/sendgrid/docs/pull/4182#discussion_r224903380)), even though the API still references it. 
This PR alters the references to whitelabeling and replaces them with the following:
Whitelabel = Sender Authentication
Domain Whitelabel = Domain Authentication
IP Whitelabel = Reverse DNS
Link Whitelabel = Link branding

docs: Remove references to legacy "Whitelabel" Verbiage 

---

packages/mail/src/mail.d.ts

From typescript docs overloads should be used if
>  ...will return two different things based on what the user has passed in
Here is not the case, so we can have one signature only where the first argument can be one thing or the other.
With this we can have a wrapper for the send that will retain all the types and allow both types on the first param.
eg:
```javascript
const wrap = <T extends Array<any>, U>(fn: (...args: T) => U) => {
return (...args: T): U => fn(...args)
}
const send = wrap(sgMail.send)
``` 
Before this PR and because both signatures had the same number of params I was having troubles (if it's possible) to retain both signatures. It was picking the last one.

chore: collapse multiple mail-send TS signatures

---

packages/helpers/classes/email-address.js
packages/helpers/classes/email-address.spec.js

fix: do not wrap names with commas in quotes

---

packages/helpers/classes/mail.js
packages/helpers/classes/mail.spec.js

Fixes bug that was introduced previously when type-checking was added to these properties.
Fixes https://github.com/sendgrid/sendgrid-nodejs/issues/1179

fix: make attachment type and disposition optional

---

packages/helpers/classes/response-error.js
packages/helpers/package.json

Fixes #1202
Remove dependency on `chalk` package and its usage in the [`ResponseError` class](https://github.com/sendgrid/sendgrid-nodejs/blob/a0f4876f4a5d9959321820f2ea7682852d3fb912/packages/helpers/classes/response-error.js#L42).
If you have questions, please file a [support ticket](https://twilio.com/help/contact), or create a GitHub Issue in this repository.

chore: remove chalk dependency

---

README.md

I'm using the @sendgrid/eventwebhook package for one of my projects, but found that it was missing from the main README, so I added it. This will allow future users of SendGrid event webhooks to more easily know of its existence and not have to roll up their own solution for validating incoming webhook events.

docs: Add eventwebhook package to main README

---

packages/client/src/client.d.ts
packages/helpers/classes/request.d.ts
packages/mail/src/mail.d.ts
test/typescript/client.ts
test/typescript/mail.ts

The MailService has a method to set a client, but it isn't exposed in typings. Adding this so there is an easier way to customize underlying agents used (for keep-alive and other connection-pooling settings) without having compilation problems (or subverting the type system by just using 'any')

chore: enhance client-related typings

---

package.json
packages/client/package.json

This change ensures that we don't pull in [Chai v4.3.0](https://www.chaijs.com/releases/) (which no longer supports Node 6) with `npm install` or `yarn install`.

fix: Node 6 build failure

---

docs/use-cases/attachments.md

fix: docs for content_id field 

---

packages/eventwebhook/src/eventwebhook.spec.js

Add example to show how to process payloads with multiple events for signed webhook verification. 
Note: The webhook verification logic itself works fine with the raw request body in the example shown [here](https://github.com/sendgrid/sendgrid-nodejs/blob/main/docs/use-cases/event-webhook.md). 
Fixes #1238

chore: add signed webhook test for multi event payload

---

packages/mail/src/classes/mail-service.js
packages/mail/src/mail.spec.js

There is no way how to add custom headers to the request through the `Mail` package. The `Client` package (as a dependency of `Mail`) already works with custom headers well enough. The test checks if the request includes the added custom header. 

fix: send email with custom headers at mail-service.js 

---

packages/client/package.json

Fixes issue #1294 . Based on the discussion [here](https://github.com/axios/axios/issues/3979). It actually seems that 0.21.4 is what's necessary to address the fix.
**All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.**
I changed the version of axios that sendgrid client uses from 0.21.1 to 0.21.4.

chore!: Bump Axios to 0.21.4 to fix ReDoS

---

test/typescript/mail.ts

I was using the tests as informal documentation so I wasn't sure whether to use the `test` or the `doc` tag but since I haven't modified any test output I'm going with `doc` as it applies more closely to how I was interpreting the code.
if you call `sgMail.setClient()` _before_ you call `sgMail.setApiKey()` then everything is great. If you call them in the order that this test does you'll forever get `Unauthorized` 401 section with `data.headers` in `node_modules/@sendgrid/client/src/classes/client.js` `createRequest()` function not including `Bearer Authorization <<YOUR_API_KEY>>`
This issue is reproducible whether you set the client / key at the top outside of a typescript class, inside the typescript class' constructor, or inside the function right before the `sgMail.send` call.
Here's …

test: fix issue with new client overriding previously set api key

---

TROUBLESHOOTING.md

docs: improve signed webhook validation instruction

---

packages/mail/src/mail.d.ts
packages/mail/src/mail.spec.js

Error for callBack function of 'send' and 'sendMultiple' methods is not
described as nullable, but it should cause error is null when emails
where successfully delivered

chore: adjust 'packages/mail/src/mail.d.ts'

---

.github/workflows/test-and-deploy.yml

https://github.com/sendgrid/sendgrid-nodejs/pull/1329#discussion_r796108313

test: set the right version for tests

---

docs/use-cases/event-webhook.md

Closes #1322 
Documents how to exclude the webhook route from `bodyParser.json()`

docs: Update docs with bodyParser exclusion for webhook signature verification

---

packages/client/README.md
packages/contact-importer/README.md
packages/helpers/README.md
packages/inbound-mail-parser/README.md
packages/mail/README.md

There's a broken link on the npm pages of each package because npm isn't aware of the notion of the monorepo. Hard-coding the URL to the image is the easiest solution to this problem.
<https://www.npmjs.com/package/@sendgrid/client>

docs:fix broken image links on npm

---

packages/eventwebhook/src/eventwebhook.d.ts

Installing `@sendgrid/eventwebhook` in a project using typescript cannot properly compile because `starkbank-ecdsa` does not provide any typings and none are available in DefinitelyTyped project either.
Right now the only way to use the module is to ourselves provide a definition of `starkbank-ecdsa` OR patch-package `@sendgrid/eventwebhook`
I've decided to change the import statement with a minimal interface of `PublicKey` which should be enough to use the package properly in a typescript project.
Technically speaking, `@types/node` is also required because you use `Buffer` in the types, but a typescript project without it would be weird so I think we can let that one as-is.

fix: Fix typings for eventwebhook.d.ts PublicKey

---

packages/helpers/classes/mail.d.ts
packages/helpers/helpers/validate-settings.js

Fixes: #1291
Allow the use of bypass options `bypass_spam_management`, `bypass_bounce_management` and `bypass_unsubscribe_management`.

feat: allow use of bypass options

---

docs/use-cases/README.md
docs/use-cases/multiple-emails-personalizations-with-substitutions.md

**All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.**
This PR adds a use case to the documentation for using substitutions. 
It wasn't easy to find how to do [substitutions to answer this StackOverflow question](https://stackoverflow.com/questions/72200424/azure-app-service-snat-port-exhaustion-on-sendgrid-connection/72312725#72312725), so I decided to contribute a sample for it.

docs: Add use case for substitutions

---

packages/mail/README.md

Some of the links in the package's [npmjs](https://www.npmjs.com/package/@sendgrid/mail) landing page are broken because of being referenced by the relative path. This pr updates the links by referencing the document using the URLs which resolves the issue. 

docs: Fix broken url on npmjs

---

.github/workflows/test-and-deploy.yml
package.json
packages/client/package.json
packages/contact-importer/package.json
packages/eventwebhook/package.json
packages/helpers/package.json
packages/inbound-mail-parser/package.json
packages/mail/package.json
packages/subscription-widget/package.json

This PR: 
Drops support for node v 6, 8, 10

feat!: node version upgrade, axios upgrade

---

packages/client/package.json

Axios has a dependency of follow-redirects which has a [vulnerability](https://github.com/advisories/GHSA-cxjh-pqwp-8mfp) in it. Axios has updated its packages to a version that doesn't include the vulnerability but now we need sendgrid to update Axios to match this.
follow-redirects is an open source, drop-in replacement for Node's http and https modules that automatically follows redirects. In affected versions follow-redirects only clears authorization header during cross-domain redirect, but keep the proxy-authentication header which contains credentials too. This vulnerability may lead to credentials leak, but has been addressed in version 1.15.6. Users are advised to upgrade. There are no known workarounds for this vulnerability.
Axios has updated to 1.15.6 in their most recent …

chore: fixed axios vulnerability CVE-2024-28849

---

CHANGELOG.md
lerna.json
packages/client/package.json
packages/contact-importer/package.json
packages/mail/package.json

The previous release was pushed to npm but the latest changes were not added to the main.

fix: Manual release.
